[[constraint]]
  name = "github.com/agext/levenshtein"
  revision = "5f10fee965225ac1eecdc234c09daf5cd9e7f7b6"

[[constraint]]
  name = "github.com/agl/ed25519"
  revision = "278e1ec8e8a6e017cd07577924d6766039146ced"

[[constraint]]
  name = "github.com/apparentlymart/go-cidr"
  revision = "7e4b007599d4e2076d9a81be723b3912852dda2c"

[[constraint]]
  name = "github.com/apparentlymart/go-textseg"
  revision = "b836f5c4d331d1945a2fead7188db25432d73b69"

[[constraint]]
  name = "github.com/armon/go-radix"
  revision = "1fca145dffbcaa8fe914309b1ec0cfc67500fe61"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.14.0"

[[constraint]]
  name = "github.com/beevik/etree"
  revision = "af219c0c7ea1b67ec263c0b1b1b96d284a9181ce"

[[constraint]]
  name = "github.com/bgentry/go-netrc"
  revision = "9fd32a8b3d3d3f9d43c341bfe098430e07609480"

[[constraint]]
  name = "github.com/bgentry/speakeasy"
  revision = "4aabc24848ce5fd31929f7d1e4ea74d3709c14cd"

[[constraint]]
  name = "github.com/blang/semver"
  revision = "2ee87856327ba09384cabd113bc6b5d174e9ec0f"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  revision = "346938d642f2ec3594ed81d874461961cd0faa76"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  revision = "1d4f4ae73768d3ca16a6fb964694f58dc5eba601"

[[constraint]]
  name = "github.com/go-ini/ini"
  revision = "766e555c68dc8bda90d197ee8946c37519c19409"

[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "1e59b77b52bf8e4b449a57e6f79f21226d571845"

[[constraint]]
  name = "github.com/hashicorp/errwrap"
  revision = "7554cd9344cec97297fa6649b055a8c98c2a1e55"

[[constraint]]
  name = "github.com/hashicorp/go-cleanhttp"
  revision = "3573b8b52aa7b37b9358d966a898feb387f62437"

[[constraint]]
  name = "github.com/hashicorp/go-getter"
  revision = "90bb99a48d86cf1d327cee9968f7428f90ba13c1"

[[constraint]]
  name = "github.com/hashicorp/go-hclog"
  revision = "ca137eb4b4389c9bc6f1a6d887f056bf16c00510"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  revision = "d30f09973e19c1dfcd120b2d9c4f168e68d6b5d5"

[[constraint]]
  name = "github.com/hashicorp/go-plugin"
  revision = "a5174f84d7f8ff00fb07ab4ef1f380d32eee0e63"

[[constraint]]
  name = "github.com/hashicorp/go-safetemp"
  revision = "b1a1dbde6fdc11e3ae79efd9039009e22d4ae240"

[[constraint]]
  name = "github.com/hashicorp/go-uuid"
  revision = "36289988d83ca270bc07c234c36f364b0dd9c9a7"

[[constraint]]
  name = "github.com/hashicorp/go-version"
  revision = "e96d3840402619007766590ecea8dd7af1292276"

[[constraint]]
  name = "github.com/hashicorp/hcl"
  revision = "a4b07c25de5ff55ad3b8936cea69a79a3d95a855"

[[constraint]]
  name = "github.com/hashicorp/hcl2"
  revision = "44bad6dbf5490f5da17ec991e664df3d017b706f"

[[constraint]]
  name = "github.com/hashicorp/hil"
  revision = "fac2259da677551de1fb92b844c4d020a38d8468"

[[constraint]]
  name = "github.com/hashicorp/logutils"
  revision = "0dc08b1671f34c4250ce212759ebd880f743d883"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "v0.11.7"

[[constraint]]
  name = "github.com/hashicorp/vault"
  revision = "9a60bf2a50e4dd1ba4b929a3ccf8072435cbdd0a"

[[constraint]]
  name = "github.com/hashicorp/yamux"
  revision = "d1caa6c97c9fc1cc9e83bbe34d0603f9ff0ce8bd"

[[constraint]]
  name = "github.com/jen20/awspolicyequivalence"
  revision = "9fbcaca9f9f868b9560463d0790aae33b2322945"

[[constraint]]
  name = "github.com/jmespath/go-jmespath"
  revision = "bd40a432e4c76585ef6b72d3fd96fb9b6dc7b68d"

[[constraint]]
  name = "github.com/keybase/go-crypto"
  revision = "93f5b35093ba15e0f86e412cc5c767d5c10c15fd"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  revision = "fc9e8d8ef48496124e79ae0df75490096eccf6fe"

[[constraint]]
  name = "github.com/mitchellh/cli"
  revision = "8a539dbef410aa4191e0bcc7a6246c104b313009"

[[constraint]]
  name = "github.com/mitchellh/copystructure"
  revision = "d23ffcb85de31694d6ccaa23ccb4a03e55c1303f"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  revision = "b8bc1bf767474819792c23f32d8286a45736f1c6"

[[constraint]]
  name = "github.com/mitchellh/go-testing-interface"
  revision = "a61a99592b77c9ba629d254a693acffaeb4b7e28"

[[constraint]]
  name = "github.com/mitchellh/go-wordwrap"
  revision = "ad45545899c7b13c020ea92b2072220eefad42b8"

[[constraint]]
  name = "github.com/mitchellh/hashstructure"
  revision = "6b17d669fac5e2f71c16658d781ec3fdd3802b69"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  revision = "53818660ed4955e899c0bcafa97299a388bd7c8e"

[[constraint]]
  name = "github.com/mitchellh/reflectwalk"
  revision = "63d60e9d0dbc60cf9164e6510889b0db6683d98c"

[[constraint]]
  name = "github.com/posener/complete"
  revision = "f4461a52b6329c11190f11fe3384ec8aa964e21c"

[[constraint]]
  name = "github.com/satori/go.uuid"
  revision = "b061729afc07e77a8aa4fad0a2fd840958f1942a"

[[constraint]]
  name = "github.com/satori/uuid"
  revision = "b061729afc07e77a8aa4fad0a2fd840958f1942a"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-template"
  version = "v0.1.1"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-tls"
  version = "v0.1.0"

[[constraint]]
  name = "github.com/ulikunitz/xz"
  revision = "0c6b41e72360850ca4f98dc341fd999726ea007f"

[[constraint]]
  name = "github.com/zclconf/go-cty"
  revision = "709e4033eeb037dc543dbc2048065dfb814ce316"

[[constraint]]
  name = "golang.org/x/crypto"
  revision = "b3c9a1d25cfbbbab0ff4780b71c4f54e6e92a0de"

[[constraint]]
  name = "golang.org/x/net"
  revision = "4b14673ba32bee7f5ac0f990a48f033919fd418b"

[[constraint]]
  name = "golang.org/x/sys"
  revision = "d8f5ea21b9295e315e612b4bcf4bedea93454d4d"

[[constraint]]
  name = "golang.org/x/text"
  revision = "6eab0e8f74e86c598ec3b6fad4888e0c11482d48"

[[constraint]]
  name = "google.golang.org/genproto"
  revision = "f676e0f3ac6395ff1a529ae59a6670878a8371a6"

[[constraint]]
  name = "google.golang.org/grpc"
  revision = "b5eab4ccac6df282ff981436a5a87554d7377c75"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "cd8b52f8269e0feb286dfeef29f8fe4d5b397e0b"
